fix: build issues in CI environment
KK-1071. The CI fails to build the application:
```
django.db.utils.ProgrammingError: relation "django_content_type"
does not exist
```